.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "BOTS" "1" "October 2011" "" ""
.
.SH "NAME"
\fBbots\fR \-\- generate your own bots for world domination
.
.SH "SYNOPSIS"
\fBbots\fR <name>
.
.SH "DESCRIPTION"
Generates a directory ready for building a javascript bot\. Once you have
generated the new directory and changed into it, you will need to run \fBnpm install\fR\|\. This will install the \fBbots\fR framework into the local \fBnode_modules\fR directory\.
.
.P
Once you\'ve installed the dependencies you can start the bot with \fBnpm
start\fR, then you can type commands and the bot will interpret them\. Try \fIhelp\fR to start with, this will tell you the commands (with a
description) that the bot knows about\.
.
.SH "FILES GENERATED"
.
.IP "\(bu" 4
\fIindex\.js\fR \- contains the main bot app\.
.
.IP "\(bu" 4
\fIpackage\.json\fR \- describes the bot and its dependencies\.
.
.IP "\(bu" 4
\fIREADME\.md\fR \- contains instructions for using the bot\.
.
.IP "" 0

